export const cardDeck = {
  jobs: [
    "Shifokor",
    "Ko‘zi yomon ko‘radigan jarroh",
    "Dasturchi",
    "Elektrik",
    "Psixolog",
    "Harbiy",
    "Oshpaz",
    "Fermer",
    "Mexanik",
    "Biolog",
    "Radio operator",
    "Suv ta’minoti ustasi",
    "Veterinar",
    "Kimyogar",
    "Arxitektor",
    "Quruvchi",
    "O‘qituvchi",
    "Tikuvchi",
    "Haydovchi",
    "Bunker dizayneri",
    "Motivatsion spiker",
    "Internet marketolog",
    "YouTube strimer",
    "Sobiq sirk artisti",
    "Uyqu bo‘yicha mutaxassis",
    "Shubhali startap asoschisi",
    "Professional bahschi",
    "Qo‘shnilar muammosini hal qiluvchi odam",
    "Xavfsizlik bo‘yicha mutaxassis",
    "Hech kim tushunmaydigan olim"
  ],

  ages: [
    "18 yosh",
    "21 yosh",
    "24 yosh",
    "27 yosh",
    "31 yosh",
    "35 yosh",
    "42 yosh",
    "49 yosh",
    "56 yosh",
    "63 yosh",
    "70 yosh, lekin o‘zini 25 yoshdek tutadi",
    "16 yosh, lekin hammani boshqarishga harakat qiladi",
    "33 yosh, pasportini yo‘qotgan",
    "45 yosh, har gapni “bizning paytimizda” deb boshlaydi",
    "29 yosh, lekin hayotdan charchagan ko‘rinadi"
  ],

  health: [
    "Sog‘lom",
    "Juda sog‘lom, lekin juda ko‘p uxlaydi",
    "Ko‘zi deyarli ko‘rmaydi",
    "Qulog‘i yaxshi eshitmaydi",
    "Allergiyasi bor",
    "Chang ko‘rsa darrov aksiradi",
    "Qon bosimi yuqori",
    "Astmasi bor",
    "Belida muammo bor",
    "Qo‘li titraydi",
    "Juda kuchli immunitetga ega",
    "Viruslarga chidamli bo‘lishi mumkin",
    "Tez charchaydi",
    "Oyoqlari kuchli, uzoq yugura oladi",
    "Jarrohlikdan yangi chiqqan",
    "Qorong‘ida vahimaga tushadi",
    "Stressda hushidan ketadi",
    "O‘ta sog‘lom, lekin har narsadan noliydi",
    "Bir qo‘li kuchsiz",
    "Tungi ko‘rishi juda yaxshi",
    "Xotirasi kuchsiz",
    "Og‘riqqa chidamli",
    "Immuniteti kuchsiz, lekin juda ehtiyotkor",
    "Yuragi sog‘lom",
    "Har 10 daqiqada dramatik yo‘taladi"
  ],

  character: [
    "Sabrli",
    "Tez jahl qiladi",
    "Jamoa bilan yaxshi ishlaydi",
    "Liderlikka intiladi",
    "Juda hazilkash",
    "Kamgap, lekin aqlli",
    "Hamma narsadan shubhalanadi",
    "Jasur",
    "O‘zini juda yuqori baholaydi",
    "Mas’uliyatli",
    "Har doim kech qoladi",
    "Va’da beradi, lekin unutib qo‘yadi",
    "Bahsda yutqazsa ham tan olmaydi",
    "Har narsani reja qiladi",
    "Kichkina muammoni ham yig‘ilish qilib muhokama qiladi",
    "Sir saqlay olmaydi",
    "Odamlarni tez ishontira oladi",
    "Nervi juda mustahkam",
    "Hamma bilan kelisha oladi",
    "Biror ishni boshlasa, oxirigacha yetkazadi",
    "Har qanday vaziyatda ovqat haqida o‘ylaydi",
    "O‘zini qahramon deb hisoblaydi",
    "Kerak paytda jim turishni biladi",
    "Panikani kulgiga aylantira oladi",
    "Bunkerda prezident bo‘lishni xohlaydi"
  ],

  phobias: [
    "Qorong‘ulikdan qo‘rqadi",
    "Tor joylardan qo‘rqadi",
    "Hasharotlardan qo‘rqadi",
    "Balandlikdan qo‘rqadi",
    "Yolg‘izlikdan qo‘rqadi",
    "Suvdan qo‘rqadi",
    "Qondan qo‘rqadi",
    "Kalamushlardan qo‘rqadi",
    "Ovozli signal tovushidan qo‘rqadi",
    "Jimlikdan qo‘rqadi",
    "Robot changyutgichdan qo‘rqadi",
    "Kichkina liftlardan qo‘rqadi",
    "Oq xalatli odamlardan qo‘rqadi",
    "Hamma unga qarab turgandek tuyuladi",
    "Telefon zaryadi tugashidan qo‘rqadi",
    "Konserva ochgichdan qo‘rqadi",
    "Mikroblardan juda qo‘rqadi",
    "Yopiq eshiklardan bezovta bo‘ladi",
    "Qattiq kulgidan qo‘rqadi",
    "Fobiyasi yo‘q, lekin buni juda ko‘p takrorlaydi"
  ],

  hobby: [
    "Bog‘dorchilik",
    "Ovqat pishirish",
    "Kitob o‘qish",
    "Sport",
    "Robototexnika",
    "Baliq ovlash",
    "Shaxmat",
    "YouTube uchun video qilish",
    "Tibbiyot maqolalarini o‘qish",
    "Kompyuter o‘yinlari",
    "Eski radiolarni tuzatish",
    "Konserva yig‘ish",
    "Har narsadan ro‘yxat tuzish",
    "Qo‘rqinchli hikoyalar aytish",
    "Mem yasash",
    "Odamlarning xarakterini taxmin qilish",
    "Uxlab qolish bo‘yicha rekord urish",
    "Mini fermerlik",
    "Raqs tushish",
    "Keraksiz, lekin qiziq faktlarni bilish",
    "O‘zini detektiv deb his qilish",
    "Qadimgi xaritalarni o‘rganish",
    "Stol o‘yinlari",
    "O‘simliklar bilan gaplashish",
    "Hamma narsani ta’mirlashga urinib ko‘rish"
  ],

  inventory: [
    "Birinchi yordam qutisi",
    "Radio aloqa qurilmasi",
    "Pichoq",
    "Chiroq",
    "Urug‘lar qutisi",
    "Suv filtri",
    "Asboblar jamlanmasi",
    "Eski xarita",
    "Powerbank",
    "Gaz niqobi",
    "17 ta paypoq",
    "Shubhali konserva",
    "Bitta singan planshet",
    "Katta skotch ruloni",
    "O‘ta kuchli fonar, lekin batareyasi kam",
    "Yarim ishlaydigan dron",
    "10 kg grechka",
    "Qo‘lda aylantiriladigan generator",
    "Eski telefon, ichida foydali rasmlar bor",
    "Bunker kalitiga o‘xshagan noma’lum kalit",
    "Qop-qora ko‘zoynak",
    "Pishloq kesadigan pichoq",
    "Hamma uchun yetmaydigan shokolad",
    "Kichik quyosh paneli",
    "Qattiq sirli chamadon"
  ],

  special: [
    "Bir marta ovoz berishni bekor qila oladi",
    "O‘ziga berilgan bitta ovozni bekor qiladi",
    "Bitta o‘yinchini himoya qila oladi",
    "O‘zining bitta kartasini almashtira oladi",
    "Bitta o‘yinchidan kartasini ochishni talab qila oladi",
    "Finalda bitta qo‘shimcha ovozga ega bo‘ladi",
    "Bir raund ovoz bermaslik huquqiga ega",
    "Bitta yopiq kartasini yolg‘ondan boshqa nom bilan aytishi mumkin",
    "Bir marta o‘zini ovozdan vaqtincha saqlab qoladi",
    "Bitta o‘yinchining ochilgan kartasini savol ostiga qo‘yadi",
    "Ikki daqiqa davomida hech kim uni savolga tuta olmaydi",
    "Bitta o‘yinchiga qo‘shimcha savol berish huquqiga ega",
    "Ovoz berishdan oldin 30 soniya qo‘shimcha nutq qiladi",
    "Bitta yomon kartasini oxirigacha yashirishga urinishi mumkin",
    "Maxsus kuchi yo‘q, lekin buni juda dramatik aytadi"
  ],

  catastrophes: [
    "Butun dunyoda Wi-Fi o‘chdi. Odamlar 3-kuni yovvoyilashdi.",
    "Yer yuzida kuchli radiatsiya tarqaldi. Tashqarida uzoq yashash deyarli imkonsiz.",
    "Global virus insoniyatning katta qismini yo‘q qildi. Faqat izolyatsiya qilingan joylar xavfsiz.",
    "Katta meteorit zarbasidan keyin shaharlar vayron bo‘ldi va oziq-ovqat zaxiralari tugamoqda.",
    "Sun’iy intellekt tizimlari nazoratdan chiqdi. Endi robotlar odamlardan parol so‘rayapti.",
    "Iqlim falokati sababli tashqarida harorat juda xavfli darajaga yetdi.",
    "Dunyodagi barcha tovuqlar bir kunda yo‘qoldi. Oziq-ovqat tizimi izdan chiqdi.",
    "Noma’lum gaz odamlarni haddan tashqari rostgo‘y qilib qo‘ydi. Jamiyat bardosh bera olmadi.",
    "Yer yuzini ulkan chang bo‘ronlari qopladi. Quyosh deyarli ko‘rinmay qoldi.",
    "Dengiz sathi ko‘tarildi. Ko‘p shaharlar suv ostida qoldi.",
    "Odamlar uyquga ketib, 3 kundan keyin uyg‘onmaydigan kasallik tarqaldi.",
    "Hayvonlar juda aqlli bo‘lib qoldi va fermalarni qaytarib olishga qaror qildi.",
    "Butun dunyoda elektr tizimi ishdan chiqdi. Faqat eski mexanik qurilmalar ishlayapti.",
    "Gigant qo‘ziqorinlar shaharlarni egallab oldi. Ularni yeb bo‘lmaydi, lekin ular juda jahldor.",
    "Global internet mem urushi real hayotga ko‘chdi. Guruhlar memlar uchun jang qilmoqda."
  ],

  bunkers: [
    "Bunker 5 yilga yetadigan oziq-ovqat, suv filtri va kichik laboratoriyaga ega. Joylar cheklangan.",
    "Bunkerda tibbiyot xonasi, issiqxona va generator bor. Lekin xavfsizlik tizimi eski.",
    "Bunker tog‘ ostida joylashgan. Unda suv manbasi bor, ammo aloqa vositalari juda kam.",
    "Bunker eski harbiy obyekt ichida. Qurol ombori bor, lekin yashash sharoiti og‘ir.",
    "Bunkerda kichik ferma, quyosh panellari va radio markaz bor. Faqat joy hammaga yetmaydi.",
    "Bunker juda qulay, lekin unda faqat bitta hammom bor. Bu muammo bo‘lishi mumkin.",
    "Bunkerda oziq-ovqat ko‘p, lekin hammasi bir xil konserva. Ruhiy holat xavf ostida.",
    "Bunkerda zamonaviy laboratoriya bor, lekin uni ishlatishni hech kim bilmasligi mumkin.",
    "Bunkerda issiqxona bor, lekin o‘simliklar juda injiq.",
    "Bunkerda eski radio bor. Ba’zan noma’lum odamlar kulib yuboradi.",
    "Bunker ichida kichik sport zali bor. Lekin trenajorlarning yarmi g‘ichirlaydi.",
    "Bunkerda katta kutubxona bor, lekin kitoblarning yarmi pazandalik haqida.",
    "Bunkerda generator bor, lekin har kuni kimdir uni tinchlantirib gaplashishi kerak.",
    "Bunkerda maxfiy xona bor. Eshigida faqat “Ochmang” deb yozilgan.",
    "Bunker hashamatli, lekin boshqaruv paneli rus tilida va juda chalkash."
  ]
};

export const cardLabels = {
  job: "Kasb",
  age: "Yosh",
  health: "Sog‘liq",
  character: "Xarakter",
  phobia: "Fobiya",
  hobby: "Hobbi",
  inventory: "Inventar",
  special: "Maxsus karta"
};