export const cardDeck = {
  jobs: [
    "Shifokor",
    "Ko‘zi yomon ko‘radigan jarroh",
    "Dasturchi",
    "Elektrik",
    "Mexanik",
    "Oshpaz",
    "Agronom",
    "Psixolog",
    "Biolog",
    "Kimyogar",
    "Veterinar",
    "Muhandis",
    "Quruvchi",
    "Tikuvchi",
    "Haydovchi",
    "Bunker dizayneri",
    "Motivatsion spiker",
    "Internet marketolog",
    "YouTube strimer",
    "Sobiq sirk artisti",
    "Uyqu bo‘yicha mutaxassis",
    "Shubhali startap asoschisi",
    "Professional bahschi",
    "Qo‘shnilar muammosini hal qiluvchi odam",
    "Xavfsizlik bo‘yicha mutaxassis",
    "Hech kim tushunmaydigan olim",
    "Radiomuhandis",
    "Hamshira",
    "Farmatsevt",
    "Robototexnik",
    "Santexnik",
    "Bog‘bon",
    "Ovchi",
    "Baliqchi",
    "Harbiy instruktor",
    "Sobiq politsiyachi",
    "Logistika mutaxassisi",
    "O‘qituvchi",
    "Tarixchi",
    "Kartograf",
    "Geolog",
    "Metrolog",
    "Energetik",
    "Suv filtri ustasi",
    "Laboratoriya assistenti",
    "Tish shifokori",
    "Nonvoy",
    "Mediator",
    "Aktyor",
    "Komik",
    "Tadbirkor",
    "UX dizayner",
    "Kiberxavfsizlik mutaxassisi",
    "Dron operatori",
    "Qutqaruvchi",
    "Feldsher",
    "Sartarosh",
    "TikTok tahlilchisi",
    "Tungi qorovul",
    "O‘zini hamma narsani bilaman deb o‘ylaydigan ekspert"
  ],

  ages: [
    "18 yosh",
    "21 yosh",
    "24 yosh",
    "27 yosh",
    "30 yosh",
    "33 yosh",
    "36 yosh",
    "39 yosh",
    "42 yosh",
    "45 yosh",
    "48 yosh",
    "51 yosh",
    "55 yosh",
    "60 yosh",
    "16 yosh, lekin juda aqlli",
    "70 yosh, tajribasi juda ko‘p",
    "28 yosh, doim kech qoladi",
    "34 yosh, jismonan kuchli",
    "40 yosh, liderlik tajribasi bor",
    "23 yosh, tez o‘rganadi",
    "52 yosh, sovuqqon qaror qiladi",
    "31 yosh, tinmay hazil qiladi",
    "25 yosh, stressga chidamli",
    "46 yosh, hammani tartibga soladi"
  ],

  health: [
    "Sog‘lom",
    "Juda sog‘lom, lekin juda ko‘p uxlaydi",
    "Ko‘zi deyarli ko‘rmaydi",
    "Qulog‘i yaxshi eshitmaydi",
    "Allergiyasi bor",
    "Astmasi bor",
    "Qo‘li jarohatlangan",
    "Oyog‘i jarohatlangan",
    "Tez charchaydi",
    "Immuniteti kuchli",
    "Yuragi zaif",
    "Qon bosimi ko‘tariladi",
    "Diabeti bor",
    "Operatsiyadan chiqqan",
    "Hech qachon kasal bo‘lmagan",
    "Doim vitamin ichadi",
    "Uyqusizlikdan qiynaladi",
    "Stressda yaxshi ishlaydi",
    "Stressda darrov qotib qoladi",
    "Xotirasi juda kuchli",
    "Xotirasi yomon",
    "Sovuqda yaxshi chidaydi",
    "Issiqda tez holsizlanadi",
    "Qo‘rqsa ham yugura oladi",
    "Qo‘rqsa joyida muzlab qoladi",
    "Ovqat tanlaydi",
    "Hammasini yeyaveradi",
    "Tez tuzaladi",
    "Dori-darmonga allergiyasi bor",
    "Karantin qoidalariga qat’iy amal qiladi",
    "Bosh og‘rig‘i tez-tez bo‘ladi",
    "Tunda yaxshi ko‘radi",
    "Kunduzi ko‘proq faol",
    "Juda baland ovozda xurrak otadi",
    "Sport bilan shug‘ullanadi",
    "Hatto zinadan chiqsa ham charchaydi",
    "Panikada nafas mashqi qila oladi",
    "Bunker havosiga tez moslashadi"
  ],

  character: [
    "Sokin va vazmin",
    "Doim lider bo‘lishni xohlaydi",
    "Bahsda hech qachon yutqazishni istamaydi",
    "Tez jahli chiqadi",
    "Hazilkash",
    "Doim shubhalanadi",
    "Odamlarni tez ishontiradi",
    "Yolg‘on gapirganda qizarib ketadi",
    "Mas’uliyatli",
    "Mas’uliyatdan qochadi",
    "Kerak paytda jim turishni biladi",
    "Panikani kulgiga aylantira oladi",
    "Bunkerda prezident bo‘lishni xohlaydi",
    "Har narsaga reja tuzadi",
    "Rejadan ko‘ra improvizatsiyani yaxshi ko‘radi",
    "Oson do‘stlashadi",
    "Hech kimga ishonmaydi",
    "Kechirimli",
    "Mayda narsaga ham xafa bo‘ladi",
    "Ko‘p gapiradi",
    "Kam gapiradi, lekin aniq gapiradi",
    "O‘zini qurbon qilishga tayyor",
    "Faqat o‘zini o‘ylaydi",
    "Tartibni yaxshi ko‘radi",
    "Xaosda ham yo‘l topadi",
    "Qiyin paytda hazil qiladi",
    "Ovoz berishda juda sovuqqon",
    "Kim kuchli bo‘lsa, o‘shanga qo‘shiladi",
    "Hamma bilan murosa qiladi",
    "Boshqalarning sirini saqlay olmaydi",
    "Katta va’dalar beradi",
    "Bajarmasa ham harakat qiladi",
    "Muzokarada kuchli",
    "Manipulyatsiyani tez sezadi",
    "O‘zi manipulyatsiya qiladi",
    "Ishonchli",
    "Shubhali darajada yoqimtoy",
    "Doim ovqat haqida o‘ylaydi",
    "Hech qachon aybini tan olmaydi",
    "O‘z xatosidan tez o‘rganadi",
    "Har gapga fakt so‘raydi",
    "Boshqalarga motivatsiya beradi",
    "Oson vahimaga tushadi",
    "Hech narsadan qo‘rqmaydigandek ko‘rinadi",
    "Ichida qo‘rqadi, tashqarida kuladi",
    "Adolatparvar",
    "Ovoz berishda hissiyotga beriladi",
    "Qoidalarga qattiq yopishadi",
    "Qoidalarni o‘z foydasiga buradi",
    "Odamlarni birlashtira oladi"
  ],

  phobias: [
    "Qorong‘ulikdan qo‘rqadi",
    "Tor joylardan qo‘rqadi",
    "Hasharotlardan qo‘rqadi",
    "Balandlikdan qo‘rqadi",
    "Yolg‘izlikdan qo‘rqadi",
    "Sukutdan qo‘rqadi",
    "Mikroblardan qo‘rqadi",
    "Suvdan qo‘rqadi",
    "Elektrdan qo‘rqadi",
    "Robotlardan qo‘rqadi",
    "Masxarabozlardan qo‘rqadi",
    "Yopiq eshiklardan qo‘rqadi",
    "Ochiq joylardan qo‘rqadi",
    "Ovoz berishdan qo‘rqadi",
    "Bunker boshqaruv panelidan qo‘rqadi",
    "Generator ovozidan qo‘rqadi",
    "Noma’lum tugmalardan qo‘rqadi",
    "Qizil chiroq yonganda vahimaga tushadi",
    "Kameralardan qo‘rqadi",
    "Katta mas’uliyatdan qo‘rqadi",
    "Shifokorlardan qo‘rqadi",
    "Qon ko‘rishdan qo‘rqadi",
    "Jim qarab turadigan odamlardan qo‘rqadi",
    "Eski radiodan chiqadigan ovozdan qo‘rqadi",
    "Bitta xonada ko‘p odam bo‘lishidan qo‘rqadi",
    "Yetakchi bo‘lishdan qo‘rqadi",
    "Hamma unga qarab tursa gapira olmaydi",
    "Konserva ochkichdan qo‘rqadi",
    "Tunda navbatchilik qilishdan qo‘rqadi",
    "Bunker eshigi yopilishidan qo‘rqadi",
    "O‘z fikrini aytishdan qo‘rqadi",
    "Hayvonlardan qo‘rqadi",
    "Virus haqidagi yangiliklardan qo‘rqadi",
    "Lift va yerosti yo‘llaridan qo‘rqadi",
    "Sirli xonalardan qo‘rqadi"
  ],

  hobby: [
    "Shaxmat o‘ynaydi",
    "Bog‘dorchilik qiladi",
    "Ovqat pishirishni yaxshi ko‘radi",
    "Survival videolar ko‘radi",
    "Podkast eshitadi",
    "Sport bilan shug‘ullanadi",
    "Kitob o‘qiydi",
    "Eski texnikalarni tuzatadi",
    "Baliq ovlaydi",
    "Memlar yig‘adi",
    "Qo‘shiq aytadi",
    "Gitara chaladi",
    "Stol o‘yinlarini yaxshi ko‘radi",
    "Psixologiya o‘rganadi",
    "Chet tillar o‘rganadi",
    "Har kuni reja yozadi",
    "Yuguradi",
    "Yoga qiladi",
    "Hammani kuzatib tahlil qiladi",
    "Kichik tajribalar qiladi",
    "Radio tinglaydi",
    "Rasm chizadi",
    "Tikuvchilik qiladi",
    "DIY videolar qiladi",
    "Komiks chizadi",
    "O‘simlik parvarishlaydi",
    "Meditatsiya qiladi",
    "Qadimgi xaritalarni yaxshi ko‘radi",
    "Sirli hikoyalar yozadi",
    "Ovoz yozib yuradi",
    "Kundalik yozadi",
    "Texnik chizmalar chizadi",
    "Bunker interyerini xayolida tuzadi",
    "Odamlarning mimikasini o‘qishni mashq qiladi",
    "Kechasi yulduzlarni kuzatadi"
  ],

  inventory: [
    "Birinchi yordam qutisi",
    "Kichik pichoq",
    "Fonar",
    "Batareykalar",
    "Suv filtri",
    "Qo‘lda aylantiriladigan generator",
    "Eski telefon, ichida foydali rasmlar bor",
    "Bunker kalitiga o‘xshagan noma’lum kalit",
    "Qop-qora ko‘zoynak",
    "Pishloq kesadigan pichoq",
    "Hamma uchun yetmaydigan shokolad",
    "Kichik quyosh paneli",
    "Qattiq sirli chamadon",
    "Radiatsiya o‘lchagich",
    "Multitool",
    "Arqon",
    "Izolyatsiya lentasi",
    "Quruq ovqat paketi",
    "Konserva ochkich",
    "Dori-darmon to‘plami",
    "Noutbuk, lekin zaryadi 12%",
    "USB fleshka",
    "Eski radio",
    "Issiq kiyim",
    "Gaz niqobi",
    "Dezinfeksiya vositasi",
    "Kichik kamera",
    "Qog‘oz xarita",
    "Kompas",
    "Magnit",
    "Kichik mikroskop",
    "Yopishqoq lenta",
    "Uyqu qopi",
    "Pazandalik kitobi",
    "Quritilgan urug‘lar",
    "Mini issiqxona to‘plami",
    "O‘yin kartalari",
    "Psixologik testlar kitobi",
    "Generator uchun ehtiyot qism",
    "Bir juft qo‘lqop",
    "Kichik bolta",
    "Suv o‘tkazmaydigan daftar",
    "Morse alifbosi yozilgan qog‘oz",
    "Qulflarni ochish to‘plami",
    "Kichik dron",
    "Tibbiy niqoblar",
    "Quloqchin",
    "Havo sifati sensori",
    "Choy paketchalari",
    "Hamma tortishadigan yagona yostiq"
  ],

  special: [
    "Bir marta ovoz berishni bekor qila oladi",
    "O‘ziga berilgan bitta ovozni bekor qiladi",
    "Bitta o‘yinchini himoya qila oladi",
    "O‘zining bitta kartasini almashtira oladi",
    "Bitta o‘yinchidan kartasini ochishni talab qila oladi",
    "Bir raund davomida ovoz bera olmaydi, lekin uni ham ovozga qo‘yib bo‘lmaydi",
    "Ikki o‘yinchini joyini almashtirib muhokamani chalg‘itadi",
    "Bitta yopiq kartani yashirincha ko‘rishi mumkin",
    "O‘zini oxirgi ovoz berishdan saqlab qoladi",
    "Bir marta qo‘shimcha dalil aytish huquqiga ega",
    "Hostdan bitta savol so‘rash huquqiga ega",
    "Ovoz berishdan oldin 30 soniya nutq qiladi",
    "Bitta o‘yinchini bir raund gapirtirmay qo‘yadi",
    "O‘zining fobiyasini yashira oladi",
    "Inventar kartasini boshqa o‘yinchi bilan almashtiradi",
    "Bitta o‘yinchining kasb kartasini ochdiradi",
    "Bir marta durangda avtomatik omon qoladi",
    "O‘ziga qarshi berilgan birinchi ovozni qaytaradi",
    "Bir raund davomida faqat savol bilan gapiradi",
    "Boshqalardan bitta ovozni olib tashlaydi",
    "O‘zining yomon kartasini kulgili dalilga aylantiradi",
    "Bitta o‘yinchini himoya qilishini e’lon qiladi",
    "Ovoz berishdan keyin natijani ko‘rmasdan bitta gap aytadi",
    "Bitta karta ochilganda uni dramatik tarzda izohlaydi",
    "O‘zini foydali ko‘rsatish uchun qo‘shimcha imkon oladi",
    "Bunkerga kirish uchun maxsus tavsiyanoma ko‘rsatadi",
    "Bir marta yakuniy muhokamada birinchi gapiradi",
    "Bir marta yakuniy muhokamada oxirgi gapiradi",
    "Bitta o‘yinchining xarakter kartasini shubha ostiga qo‘yadi",
    "O‘zining inventarini ikki baravar foydali deb e’lon qiladi",
    "Bitta o‘yinchini 1 daqiqa reklama qilishi kerak bo‘ladi",
    "Bitta o‘yinchiga savol beradi, u faqat ha yoki yo‘q deb javob beradi",
    "Bir marta o‘ziga ovoz berishni taqiqlaydi",
    "Bunker qoidasiga bitta kichik o‘zgartirish taklif qiladi",
    "O‘yin oxirida o‘ziga bonus nutq oladi"
  ],

  catastrophes: [
    "Butun dunyoda Wi-Fi o‘chdi. Odamlar 3-kuni yovvoyilashdi.",
    "Yer yuzida kuchli radiatsiya tarqaldi. Tashqarida uzoq yashash deyarli imkonsiz.",
    "Global virus insoniyatning katta qismini yo‘q qildi. Faqat izolyatsiya qilingan joylar xavfsiz.",
    "Katta meteorit zarbasidan keyin shaharlar vayron bo‘ldi va oziq-ovqat zaxiralari tugamoqda.",
    "Sun’iy intellekt tizimlari nazoratdan chiqdi. Endi robotlar odamlardan parol so‘rayapti.",
    "Yer yuzini zaharli tuman qopladi. Faqat filtrli joylarda yashash mumkin.",
    "Okean sathi keskin ko‘tarildi. Ko‘p shaharlar suv ostida qoldi.",
    "Muzlik davri boshlandi. Issiqlik manbalari eng katta boylikka aylandi.",
    "Quyosh chaqnashi butun elektronikani ishdan chiqardi.",
    "Oziq-ovqat zanjiri buzildi. Ferma va urug‘lar oltindan qimmat.",
    "Yer qimirlashlari ketma-ket davom etmoqda. Yerosti joylari ham xavfli.",
    "Atmosferada kislorod kamaymoqda. Havo nazorati eng muhim vazifa.",
    "Tashqarida noma’lum hasharotlar juda tez ko‘paymoqda.",
    "Ichimlik suvi manbalari zaharlangan. Filtrlash texnologiyasi hal qiluvchi ahamiyatga ega.",
    "Katta shaharlar tashlab ketilgan. Faqat kichik guruhlar omon qolmoqda.",
    "Global aloqa uzildi. Nima bo‘layotganini hech kim aniq bilmaydi.",
    "Odamlar xotirasini yo‘qotadigan virus tarqaldi.",
    "Barcha hayvonlar noodatiy tajovuzkor bo‘lib qoldi.",
    "Tunda tashqarida noma’lum signal eshitiladi va odamlar vahimaga tushadi.",
    "Yer yuzida doimiy chang bo‘ronlari boshlandi.",
    "Energiya inqirozi sababli barcha davlat tizimlari qulab tushdi.",
    "Robot changyutgichlar bosh ko‘tardi. Bu kulgili tuyuladi, lekin ular juda ko‘p.",
    "Internetdagi barcha yolg‘on yangiliklar real hayotga ta’sir qila boshladi.",
    "Yerga yaqin sun’iy yo‘ldoshlar qulab tushmoqda.",
    "Global sovuq sababli issiq joylar uchun urush boshlandi.",
    "Noma’lum bakteriya metallni yemira boshladi.",
    "Tashqaridagi odamlar uyqu rejimini yo‘qotgan va agressiv.",
    "Barcha bank tizimlari o‘chdi. Endi konserva yangi valyuta.",
    "Katta elektromagnit portlashdan keyin faqat eski texnikalar ishlayapti.",
    "Bunkerlar orasida resurs uchun yashirin raqobat boshlandi."
  ],

  bunkers: [
    "Bunker 5 yilga yetadigan oziq-ovqat, suv filtri va kichik laboratoriyaga ega. Joylar cheklangan.",
    "Bunkerda tibbiyot xonasi, issiqxona va generator bor. Lekin xavfsizlik tizimi eski.",
    "Bunker tog‘ ostida joylashgan. Unda suv manbasi bor, ammo aloqa vositalari juda kam.",
    "Bunker eski harbiy obyekt ichida. Qurol ombori bor, lekin yashash sharoiti og‘ir.",
    "Bunkerda kichik ferma, quyosh panellari va radio markaz bor. Faqat joy hammaga yetmaydi.",
    "Bunker juda qulay, lekin unda faqat bitta hammom bor. Bu muammo bo‘lishi mumkin.",
    "Bunkerda oziq-ovqat ko‘p, lekin hammasi bir xil konserva. Ruhiy holat xavf ostida.",
    "Bunkerda zamonaviy laboratoriya bor, lekin uni ishlatishni hech kim bilmasligi mumkin.",
    "Bunkerda issiqxona bor, lekin o‘simliklar juda injiq.",
    "Bunkerda eski radio bor. Ba’zan noma’lum odamlar kulib yuboradi.",
    "Bunker ichida kichik sport zali bor. Lekin trenajorlarning yarmi g‘ichirlaydi.",
    "Bunkerda katta kutubxona bor, lekin kitoblarning yarmi pazandalik haqida.",
    "Bunkerda generator bor, lekin har kuni kimdir uni tinchlantirib gaplashishi kerak.",
    "Bunkerda maxfiy xona bor. Eshigida faqat Ochmang deb yozilgan.",
    "Bunker hashamatli, lekin boshqaruv paneli rus tilida va juda chalkash.",
    "Bunker yerosti metro bekatida qurilgan. Yo‘llar ko‘p, lekin hammasi xavfsiz emas.",
    "Bunker sobiq maktab podvalida. Taxta, bo‘r va juda ko‘p stullar bor.",
    "Bunkerda AI yordamchi bor, lekin u juda kinoyali javob beradi.",
    "Bunkerda suv ko‘p, ammo isitish tizimi zaif.",
    "Bunkerda qulay yotoqlar bor, lekin navbatchilik jadvali juda qattiq.",
    "Bunker kosmik stansiya uslubida qurilgan. Lekin oynalar tashqariga qaramaydi.",
    "Bunkerda yaxshi oshxona bor, lekin oshpaz bo‘lmasa hamma janjallashadi.",
    "Bunkerda kichik kasalxona bor, ammo dori cheklangan.",
    "Bunkerda hayvonlar uchun alohida xona bor. Nima uchun kerakligi noma’lum.",
    "Bunkerda kuchli server xonasi bor. Elektr yetmasa hammasi o‘chadi.",
    "Bunkerda 3D printer bor, lekin material juda kam.",
    "Bunkerda bolalar maydonchasi bor, lekin o‘yinchilar katta yoshda.",
    "Bunkerda yaxshi xavfsizlik eshigi bor, lekin kalit kimdaligi noma’lum.",
    "Bunkerda kinozal bor. Film tanlash esa har kuni katta bahsga sabab bo‘ladi.",
    "Bunkerda eski arxiv bor. Unda foydali ma’lumot ham, keraksiz hujjat ham juda ko‘p."
  ]
};

export const cardLabels = {
  job: "Kasb",
  age: "Yosh",
  health: "Sog‘liq",
  character: "Xarakter",
  phobia: "Fobiya",
  hobby: "Hobbi",
  inventory: "Inventar",
  special: "Maxsus karta"
};